# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a23c5121dd46553667d25c7763bb7030f8eafef8975f9ba71f3fd9c91d6c75053701df3bed383516d3f40d67683821deae0926a38267a226467be5a227c85c0b

test:
  secret_key_base: 74d3ba5f457ddbea09e4073f50c08d3e0c274f9829bfa95078876906eff558698cee671e0f01ef8c6b877017ef2650bde0c599dda8047b9e06050961f8fc481f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
